extern int total_nuc;
extern char na_name[17];
extern int LOW_COV;
extern int MIN_END, END_LEG, INT_LEG, MIN_OTH_LEN;
extern int MIN_INT;
extern int idum;
extern int max_seq;
extern int MAX_TMP_LEG;
extern int MAX_BRA;
extern int g, h;
extern int W[15][15];
extern double MIN_PERC, MIN_IDENTITY;
extern int start_ent, end_ent, band;
extern long n_ban;
extern int overlaplen;
extern int word_len;
extern int SHORTLEG;
extern int MIN_WHIRL_SIZE;
extern int SHORTCYC;
extern int SHORTEND;
extern char END_MERGE;
extern int SEGLEN;
extern int total_color;
extern double color_box[21][3];
